### ISSUE TITLE
iOS11 hangs on VR prompt

### ISSUE THREAD

**Issue by jsantell** [immersive-web/webvr-polyfill#294]
When running an example on https://poly.google.com on iOS11, when entering VR, the VR prompt "place your phone into your cardboard viewer" hangs.

edit: removing iPhone 7+ distinction, was due to orientation lock :cry:  (but still exists in other iPhone models)

**Comment by jsantell** [comment]
Confirmed on iOS 11.1.2, iPhone 6s, screen orientation unlocked

**Comment by cvan** [comment]
I haven't dug into this yet, but if you've given this some thought, what's your best guess on the easiest workaround (and hopefully a viable long-term solution)? I can experiment, but I figured I'd ask first. Thanks, @jsantell!

**Comment by jsantell** [comment]
@cvan I haven't been able to recreate this again on any version of iOS11 over the last few months with screen orientation unlocked, and suspect either something changed in a later iOS11 build, or screen orientation was ultimately locked

**Comment by jsantell** [comment]
Haven't seen this in a few months; closing.
