### ISSUE TITLE
Why not work with some devices?

### ISSUE THREAD

**Issue by Hanzofm** [immersive-web/webvr-polyfill#315]
##### Description:

I have loaded the example that is in the repo:

https://github.com/immersive-web/webvr-polyfill/tree/master/examples

And in a LG Nexus 5 device works correctly and moves screen with the device motion, but on other devices like Samsung Galaxy J5 the screen not moves with the device motion.

**The project is loaded in a Iframe inside a ionic project**

##### Additional Information:

* webvr-polyfill version: 0.10.5
* Browser name/version/release channel:
* Operating System: Nexus 5 Android 6.0.1(OK) Samsung J5 Android 7.0(KO)

**Comment by JaviChaques** [comment]
I have the same problem with different devices.
It works on Chrome v59 but doesn't work on Chrome v65.

**Comment by jsantell** [comment]
@JaviChaques are you on the latest version of the polyfill? You could be running into [Chrome m65's issues with devicemotion otherwise](https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3).

@Hanzofm Check out this section on [iframes in the cardboard-vr-display](https://github.com/immersive-web/cardboard-vr-display#iframes)

**Comment by StudioZAAK** [comment]
it occurs that on chrome 65 (yes using the latest polyfill) on android 7 webvr polyfill doesn't work at all. same behaviour when visiting aframe, krpano demos and so on. what went wrong with chrome 65 on android? running over 100 client projects based upon webvr-polyfill and i have no clue if it's even possible to fix it. (tested on samsung galaxy s7, s8, nexus 5 + 6)

**Comment by jsantell** [comment]
Chrome m65 is a platform issue and there's nothing more we can do on the polyfill side, unfortunately
