### ISSUE TITLE
Neither device motion nor device orientation can reach cross domain iframe in Chrome 66

### ISSUE THREAD

**Issue by fyuvb** [immersive-web/webvr-polyfill#316]
##### Description:

I tested on my Pixel with Chrome 66 and it seemed that both devicemotion and deviceorientation cannot reach cross domain iframe in Chrome66.

##### Additional Information:

* webvr-polyfill version: v0.10.3
* Browser name/version/release channel: Chrome beta 66, Google PlayStore.
* Operating System: Android

**Comment by jsantell** [comment]
Have you tried any of [these techniques](https://github.com/immersive-web/cardboard-vr-display#iframes)? Is this new to Chrome m66?

**Comment by fyuvb** [comment]
I tried adding those tag to iframe and it worked. Thanks! Well. this should be new to Chrome m66 because I tried Chrome m65 and deviceorientation could reach cross domain iframe without those tags on iframe. 

Thank you!

**Comment by jsantell** [comment]
Glad it worked! It's a permissions issue and deviceorientation is an older API, so makes sense that's locked down a bit now. I'll add documentation indicating what to do in the iframe case so that it's more noticeable here. Thanks!
