### ISSUE TITLE
Support for Oculus Go

### ISSUE THREAD

**Issue by paulmasson** [immersive-web/webvr-polyfill#321]
The Android WebView that ships with the Oculus Go is based on Chrome 52, which of course doesn't support WebVR. In experimenting with your polyfill, I can get the VR to present from the WebView, albeit in low resolution, but I can't look around the scene: it's stuck in the forward direction.

What should I be looking to adjust when using the polyfill on Oculus Go?

Are there any plans to support this device more fully?

Thanks.

**Comment by jsantell** [comment]
It sounds like there's possibly no `devicemotion` events -- do you get any events for accelerationIncludingGravity here on the Oculus Go?: https://devicemotion-events.glitch.me/

**Comment by paulmasson** [comment]
The web page shows six lines of labels but no entries after them. I'm assuming there should be numeric values after the colons. The JS console in Chrome displays this error repeatedly:

`Uncaught TypeError: Cannot read property 'accelerationIncludingGravity' of undefined`

**Comment by jsantell** [comment]
Sounds like the Oculus Go does not have devicemotion events, which powers the webvr polyfill -- not sure how to make this work without that

**Comment by paulmasson** [comment]
@jsantell thanks for taking the time to provide feedback. I've got a bunch of questions into Oculus about this. Let's see if they have anything useful to report.

**Comment by jsantell** [comment]
Oculus Go should have WebVR support, what's the reason for needing the polyfill in this case?

**Comment by paulmasson** [comment]
The main Oculus browser does indeed support WebVR and works fine for viewing websites. If one wants to package a web app for deployment as an Android app, then you're stuck using the Android WebView which doesn't support WebVR.

I did hear back from an Oculus employee who told me that they are aware of the WebView limitation and plan on upgrading the default WebView, but he couldn't give me a timeframe. He also said that support for devicemotion events is planned, but it sounds like the Android WebView will support WebVR before that happens.

**Comment by jsantell** [comment]
Great, thanks for the update! @paulmasson

**Comment by cstensonpv** [comment]
Do we have any update about this in recent time? Will do a little investigation of my own and update my post if I find anything.

**Comment by jsantell** [comment]
I believe Oculus browser should work with this library: https://github.com/immersive-web/webvr-polyfill/issues/334

**Comment by cstensonpv** [comment]
Basicly what I would like is to run it on oculus in the Android Webview.

**Comment by paulmasson** [comment]
@cstensonpv as of firmware version 3.55 the default Android WebView is reported as version 61 for the Oculus Go. Since Chrome for Android has had WebVR support starting with version 56, the current Oculus Go WebView should handle WebVR just fine, although I haven't tested it yet. The Oculus employee told me last year that WebVR is the preferred development route, rather than relying on the (nonexistent) devicemotion events that power this polyfill.

**Comment by cstensonpv** [comment]
It handles WebVR fine. However I'm struggling with how to force webvr to render 2eyes and not render as a screen. Any suggestions?

**Comment by paulmasson** [comment]
@cstensonpv I'm not understanding what you're trying to achieve. Why would you want to display anything other than a single screen in VR? What precisely is the use case?

**Comment by cstensonpv** [comment]
What I would like to do is enabling small expereinces through web vr to be a complement to mine already in place vr and handheld ar apps. Adding value using webvr to these experiences. For handheld AR it works fine. but in VR I would like to skip the first step. Aka press enter and go directly into VR.

**Comment by paulmasson** [comment]
@cstensonpv use a page `onload` function to select the WebVR button from the DOM and programmatically click it. I've gotten that to work in the past.
