### ISSUE TITLE
Camera magnifies device rotation on Android React Native webview

### ISSUE THREAD

**Issue by naftalibeder** [immersive-web/webvr-polyfill#326]
##### Description:

On Android, in React Native's [WebView](https://facebook.github.io/react-native/docs/webview), the polyfill causes the camera to be extremely sensitive to device motion - a slight tilt rotates the scene many times. It otherwise is accurately mapping camera rotation to device rotation - just a multiplier issue.

Rotation works correctly in the component on iOS, and also on the Samsung system web browser.

Is there a field I can adjust to alter the rotation intensity? Or is this a known issue with the React browser on Android?

* webvr-polyfill version: 0.10.6
* Browser name/version/release channel: React Native (0.55.4) WebView
* Operating System: Android 8.0.0

**Comment by jsantell** [comment]
What browser engine is React Native's WebView? There were some regressions in recent Chromium versions that you may be running into: https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3

**Comment by naftalibeder** [comment]
I re-integrated the polyfill from scratch, and now I can't reproduce the problem - it's working correctly on Android. I'll keep an eye out if it resurfaces.
