### ISSUE TITLE
An attempt to assign pose to readonly VRFrameData.pose throws exception

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/webvr-polyfill#334]
https://github.com/immersive-web/webvr-polyfill/blob/124f7112ae23641c55eb19700d1389c9ac14eab4/build/webvr-polyfill.js#L641

This line throws an exception when frameData is an instance of actual, non-polyfilled VRFrameData. This scenario is possible when native WebVR is supported AND PROVIDE_MOBILE_VRDISPLAY is set to false. For the PROVIDE_MOBILE_VRDISPLAY itself I will open a separate issue, since the logic around it seems strange.

**Comment by jsantell** [comment]
Thanks for filing @Artyom17! That line can be found here in the cardboard-vr-display repo: https://github.com/immersive-web/cardboard-vr-display/blob/d709396dbbcc8e2b7c5c02cd8c30852667ebd8c7/src/util.js#L442

If WebVR is supported and PROVIDE_MOBILE_VR_DISPLAY is false, the polyfill shouldn't do anything: https://github.com/immersive-web/webvr-polyfill/blob/124f7112ae23641c55eb19700d1389c9ac14eab4/src/webvr-polyfill.js#L39, how is the polyfill being executed?

**Comment by Artyom17** [comment]
So, I am not sure how this supposed to work, tbh and whom to contact about this issue. To me, this getPolyfillDisplays function looks pretty much internal and AFRAME is using it "illegally". Am I correct?

**Comment by jsantell** [comment]
I don't remember all the rational behind this function or if it's intended to be used (definitely at least a power-user feature), but this does sound like an A-Frame issue considering the configuration, but we could also have an exception for the forcing of a polyfilled VRDisplay when viewing in Oculus, but A-Frame would have to update it upstream anyway. What do you think?

**Comment by jsantell** [comment]
That being said, if removing that check in #335 fixes it here, that sounds uncontroversial!

**Comment by jsantell** [comment]
@Artyom17 is this still an issue?

**Comment by Artyom17** [comment]
@jsantell I haven't tried the very latest version, but since #335 landed - I think it shouldn't be an issue anymore.
