### ISSUE TITLE
Customizing visor profile?

### ISSUE THREAD

**Issue by StarStep** [immersive-web/webvr-polyfill#339]
Hi, how do you calculate the right distortion parameters for your visor?
Is there any tool that we can use to find out the right values?
Thanks

**Comment by jsantell** [comment]
[Here's a few resources](https://support.google.com/cardboard/manufacturers) on generating a cardboard viewer profile, specifically [this section](https://support.google.com/cardboard/manufacturers/answer/6321873?hl=en&ref_topic=6321404). You can then add any viewers you want to WebVR polyfill with the [`ADDITIONAL_VIEWERS` option](https://github.com/immersive-web/webvr-polyfill/blob/ceb80d0e2d1d66e318782e30d89e0a09ca4857cd/src/config.js#L34)

**Comment by StarStep** [comment]
Uh cool, works fine. Some days back the profile generator was broke.
How about changing thoose values in realt time? Can it be done?
Kinda realt-time adjustment, becouse making one for each visor
maybe not the best solution :D

**Comment by jsantell** [comment]
Changing the values of the viewer distortion in real time? That's a very specific use case, you could hack [cardboard-vr-display](https://github.com/immersive-web/cardboard-vr-display) probably to handle this if you're wanting to use that to create profiles

**Comment by StarStep** [comment]
Thanks @jsantell

**Comment by jsantell** [comment]
:tada:
