### ISSUE TITLE
is webvr-polyfill compatible with the newest versions of THREE.js?

### ISSUE THREAD

**Issue by iambumblehead** [immersive-web/webvr-polyfill#340]
##### Description:

I updated packages in a webvr-polyfill-using application and now [see the black screen reported here][0] in Samsung 8, Chrome (the only device I have for testing this). Previously this worked fine.

the latest versions of THREE.js no longer include VREffect and VRControls scripts. Which version of webvr-polyfill and THREE.js should we use?

[0]: https://github.com/immersive-web/webvr-polyfill/issues/330

##### Additional Information:

* webvr-polyfill version: 0.10.10
* Browser name/version/release channel: Chrome 72.0.3626.105
* Operating System: Samsung

**Comment by jsantell** [comment]
Three has support for WebVR via `renderer.vr.enabled = true`, check out the demos for that.

Separately, the webvr polyfill can be included to provide the WebVR API if the platform does not exist

**Comment by iambumblehead** [comment]
@jsantell I found that, in my Samsung 8 chrome browser, it is necessary to visit chrome://flags/ to enable support for vr mode there and so I will probably continue using webvr-polyfill.

Do you know, is there is a way to use webvr-polyfill by and three.js without VRControls and VREffect scripts, or are those scripts required for webvr-polyfill to be used with three.js?

**Comment by iambumblehead** [comment]
@jsantell is Web VR commonly supported in phone browsers? Would you still recommend using native Web VR, even though it is not supported in the current Samsung 8 chrome browser?

What are your thoughts and recommendations?

**Comment by jsantell** [comment]
> @jsantell I found that, in my Samsung 8 chrome browser, it is necessary to visit chrome://flags/ to enable support for vr mode there and so I will probably continue using webvr-polyfill.
> 
> Do you know, is there is a way to use webvr-polyfill and three.js without VRControls and VREffect scripts, or are those scripts required for webvr-polyfill to be used with three.js?

VRControls and VREffect are no longer necessary https://github.com/immersive-web/webvr-polyfill/issues/340#issuecomment-473320935

> @jsantell is Web VR commonly supported in phone browsers? Would you still recommend using native Web VR, even though it is not supported in the current Samsung 8 chrome browser?
> 
> What are your thoughts and recommendations?

Here's the most accurate support matrix I'm aware of: https://caniuse.com/#search=webvr. The polyfill is still necessary to support a majority of users (most notably at the moment, Chrome, which is supporting the in-flux WebXR API)

**Comment by iambumblehead** [comment]
@jsantell thank you
