### ISSUE TITLE
black screen is rendered when VREffects script is not used with webvr-polyfill

### ISSUE THREAD

**Issue by iambumblehead** [immersive-web/webvr-polyfill#341]
##### Description:

[Per discussion in this ticket,][0] I removed VREffects from an application that uses webvr-polyfill and now a black screen appears in VR mode.

Many of these appear in the debug window console,
```
[.WebGL-0x7fa64b0c3400]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete
```
And finally
```
WebGL: too many errors, no more errors will be reported to the console for this context.
```

The relevant part of my script looks like this...
```javascript
    getVReffect ( canvas, renderer ) {
        let parentelem = canvas.parentElement;
        let [ w, h ] = [ parentelem.offsetWidth, parentelem.offsetHeight ];

        // let effect = new THREE.VREffect( renderer );
        // effect.setSize( w, h );
        // effect.renderer = renderer;
        // return effect;

       renderer.vr.enabled = true
       renderer.setSize( w, h )
       renderer.renderer = renderer;

       return renderer;
    }
```

[0]: https://github.com/immersive-web/webvr-polyfill/issues/340

##### Additional Information:

* webvr-polyfill version: 0.10.10
* Browser name/version/release channel: Chrome 72.0.3626.105
* Operating System: Samsung

**Comment by iambumblehead** [comment]
I am [aware of native VR support,][0] but want to continue using the polyfill for environments that do not support that.

[0]: https://threejs.org/docs/#manual/en/introduction/How-to-create-VR-content

**Comment by iambumblehead** [comment]
Actually, this is working when I use the WebVR script in the three.js libraries --nice :)
```javascript
       renderer.vr.enabled = true
       renderer.setSize( w, h )
       renderer.renderer = renderer;

       document.getElementById('three-container').appendChild( WEBVR.createButton( renderer ) );

       return renderer;
```

**Comment by jsantell** [comment]
Great to hear you got it working!
