### ISSUE TITLE
devicemotion event support is removed from chrome 74 on using http:// protocol. works fine with https://

### ISSUE THREAD

**Issue by amanonymous** [immersive-web/webvr-polyfill#345]
webvr-polyfill.js:2292 [Deprecation] The `devicemotion` event is deprecated on insecure origins and will be removed in M76, around July 2019. **Event handlers can still be registered but are no longer invoked since M74,** around April 2019. See https://www.chromestatus.com/feature/5688035094036480 for more details.

As a result, device motion does not cause any change to the loaded content on mobile.

**Comment by SrushtiITG** [comment]
do not work with https://

**Comment by jsantell** [comment]
Thanks for filing! Chrome will use the sensor API (replacing devicemotion) when it exists, only available on secure origins.

Closing this since I'm not sure that there's anything we can do on the polyfill side of things. Please reopen if I'm wrong!
