### ISSUE TITLE
Polifyll wont work on iOS - Reproducible example inside

### ISSUE THREAD

**Issue by ivnnv** [immersive-web/webvr-polyfill#356]
The polyfill wont work on iOS, the view doesn't get updated while moving the device.
Even after requiring permissions and https on the site, when on the scene, the module tries to get the data from
`var rotRate = deviceMotion.rotationRate;`
and then:
`this.gyroscope.set(rotRate.alpha, rotRate.beta, rotRate.gamma);`

And then the console shows hundreds of errors (one per frameloop)
![rotRate](https://user-images.githubusercontent.com/23552631/80430106-fc50c580-88ed-11ea-80bf-4d5ab4443996.png).

I have created a fork (and a [PR](https://github.com/immersive-web/webxr-samples/pull/71)) on the webxr-samples repo with which has a reproducible demo with the requiring permissions button to easily reproduce this issue on any iOS device:
https://ivnnv.github.io/webxr-samples/

PS: I have tried a workaround bypassing the motion capability detection here:
![orientation-types](https://user-images.githubusercontent.com/23552631/80430426-e099ef00-88ee-11ea-8910-8a42131b7641.png)
to attach to deviceorientation instead devicemotion event, but the alpha, beta, gamma values sent to `deviceOrientationQ.setFromEulerYXZ` doesnt work neither.
 

* webvr-polyfill version: 0.10.11
* Browser name/version/release channel: Safari 13.4.1
* Operating System: iOS

**Comment by GiuseppePennisi** [comment]
is there any update on this problem?

**Comment by ivnnv** [comment]
This should be fixed now because they updated cardboard-vr-display to 1.0.19.
Btw, you are welcome @jsantell ... It could have been nice to have my fix PRed into the repo instead copy-pasting into your own PR because maybe for you its not important but for a random developer having its PR merged in a international organization repo is something to be prod of.

**Comment by GiuseppePennisi** [comment]
ok, thanks. If I can ask, how did you request permissions? I follow this [https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140](guide) but it doesn't work.

**Comment by ivnnv** [comment]
I also created another PR on [the webxr-examples repo](https://github.com/immersive-web/webxr-samples/pull/71) that shows how to approach requesting permissions prior to get into vr/xr mode (mandatory for iOS)

**Comment by jsantell** [comment]
@ivnnv unfortunately, merging things outside of Github UI separates committer and authoring in some of its displays, but your [contribution](https://github.com/immersive-web/cardboard-vr-display/commit/de9678d8f077ceeddf9873bb81ee43b36e9d9651) is still attributed to you, and you are rightfully in the [list of contributors](https://github.com/immersive-web/cardboard-vr-display/graphs/contributors) -- contribution credit is absolutely important, so I hope this clarifies things. And thank you!

@GiuseppePennisi with https://github.com/immersive-web/cardboard-vr-display/pull/42 landing, webvr-polyfill 0.10.12 and up should use the latest cardboard-vr-display with the fix. Please reopen if you're still running into any issues
